/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ctphatsinh;

import dao.CT_PhatSinhDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CTPhatSinh;
import model.Kho;
import model.PhatSinh;
import model.VatTu;

/**
 *
 * @author khue
 */
public class QLCT_PhatSinh extends javax.swing.JFrame {
    
    private CTPhatSinh ctpsEdit;
    private CT_PhatSinhDao ctpsDao = new CT_PhatSinhDao();
    private DefaultTableModel tableModel;
    /**
     * Creates new form QLCT_PhatSinh
     */
    public QLCT_PhatSinh() {
        initComponents();
        this.setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tableCTPT.getModel();
        loadTable(ctpsDao.findAll());
    }

     void loadTable(List<CTPhatSinh> list) {
        tableModel.setRowCount(0);
        for (CTPhatSinh ctps : list) {
            tableModel.addRow(new Object[]{
                ctps.getPhatsinh().getPhieu(),
                ctps.getVatTu().getMaVT(),
                ctps.getSoluong(),
                ctps.getDongia(),
                ctps.getKho().getMaKho(),
                ctps.getLydo(),
            //    ctps.getPhatsinh().getHotenKH(),
                ctps.getVatTu().getTenVT(),
            //    ctps.getKho().getTenKho()
                ctps.getPhatsinh().getNgay()
                
            });
        }
    }
     public String laymakho(){
         return tf_makho.getText().toString();
     }
    
    //        private int soluong ;
//    private float dongia;
//    private String lydo ;
//    private PhatSinh phatsinh =new PhatSinh();
//    private VatTu vatTu=new VatTu();
//    private Kho kho =new Kho();
    
     private CTPhatSinh getCtPsSearch() {
        CTPhatSinh ctpsSearch = new CTPhatSinh();
        PhatSinh phatSinh = new PhatSinh();
        phatSinh.setPhieu(tf_phieu.getText());
    //    phatSinh.setHotenKH(tf_hotenkh.getText());
        Kho kho = new Kho();
        kho.setMaKho(tf_makho.getText());
    //    kho.setTenKho(tf_tenkho.getText());
        VatTu vt= new VatTu();
        vt.setMaVT(tf_mavt.getText());
     // vt.setTenVT(tf_tenvt.getText());
        ctpsSearch.setSoluong(Integer.parseInt(tf_soluong.getText()));
        ctpsSearch.setDongia(Float.parseFloat(tf_dongia.getText()));
        ctpsSearch.setLydo(tf_lydo.getText());
        ctpsSearch.setKho(kho);
        ctpsSearch.setPhatsinh(phatSinh);
        ctpsSearch.setVatTu(vt);
        return ctpsSearch;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_phieu = new javax.swing.JTextField();
        tf_mavt = new javax.swing.JTextField();
        tf_soluong = new javax.swing.JTextField();
        tf_dongia = new javax.swing.JTextField();
        tf_makho = new javax.swing.JTextField();
        tf_lydo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCTPT = new javax.swing.JTable();
        timkiem = new javax.swing.JButton();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 550));

        jLabel1.setText("Phieu");

        jLabel2.setText("MaVT");

        jLabel3.setText("SoLuong");

        jLabel4.setText("DonGia");

        jLabel5.setText("MaKho");

        jLabel6.setText("Ly Do");

        tf_phieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_phieuActionPerformed(evt);
            }
        });

        tf_mavt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mavtActionPerformed(evt);
            }
        });

        tableCTPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Phieu", "MaVT", "SoLuong", "DonGia", "MaKho", "LyDo", "ngay"
            }
        ));
        jScrollPane1.setViewportView(tableCTPT);

        timkiem.setText("HienThi");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        them.setText("Them");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setText("Sua");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        xoa.setText("Xoa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        jLabel7.setText("Bang ke chung tu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_phieu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tf_mavt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(them)
                                        .addGap(71, 71, 71)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(sua)
                                .addGap(94, 94, 94)
                                .addComponent(xoa)
                                .addGap(94, 94, 94)
                                .addComponent(timkiem)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_makho, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(tf_makho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_phieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tf_mavt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timkiem)
                            .addComponent(them)
                            .addComponent(sua)
                            .addComponent(xoa))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        try {
            String id = tableModel.getValueAt(tableCTPT.getSelectedRow(), 0).toString();
            int ok = JOptionPane.showConfirmDialog(rootPane, "Xóa  ?");
            if (ok == JOptionPane.YES_OPTION) {
                boolean r = ctpsDao.deleteByPhieu(id);
                if (!r) {
                    JOptionPane.showMessageDialog(rootPane, "Thất bại !");
                } else {
                    loadTable(ctpsDao.findAll());
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn ?");
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
      //  try {
            String id = tableModel.getValueAt(tableCTPT.getSelectedRow(), 0).toString();
            ctpsEdit = ctpsDao.findByPhieu(id);
            SuaCT_PhatSinh suaCT_PhatSinh = new SuaCT_PhatSinh(this, rootPaneCheckingEnabled);
            suaCT_PhatSinh.setVisible(true);
            suaCT_PhatSinh.setLocationRelativeTo(null);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(rootPane, "Chưa chọn  ?");
//        }
    }//GEN-LAST:event_suaActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        ThemCT_PhatSinh themCT = new ThemCT_PhatSinh(this, rootPaneCheckingEnabled);
        themCT.setVisible(true);
        themCT.setLocationRelativeTo(null);
    }//GEN-LAST:event_themActionPerformed

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
        // TODO add your handling code here:
        DSCT_PhatSinh inDanhSach=new DSCT_PhatSinh(this, rootPaneCheckingEnabled);
        inDanhSach.setVisible(true);
    }//GEN-LAST:event_timkiemActionPerformed

    private void tf_phieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_phieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phieuActionPerformed

    private void tf_mavtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mavtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mavtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLCT_PhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLCT_PhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLCT_PhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLCT_PhatSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLCT_PhatSinh().setVisible(true);
            }
        });
    }
    
    public CTPhatSinh getctpsEdit() {
        return ctpsEdit;
    }

    public void setctpsEdit(CTPhatSinh ctpsEdit) {
        this.ctpsEdit = ctpsEdit;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sua;
    private javax.swing.JTable tableCTPT;
    private javax.swing.JTextField tf_dongia;
    private javax.swing.JTextField tf_lydo;
    private javax.swing.JTextField tf_makho;
    private javax.swing.JTextField tf_mavt;
    private javax.swing.JTextField tf_phieu;
    private javax.swing.JTextField tf_soluong;
    private javax.swing.JButton them;
    private javax.swing.JButton timkiem;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables



}
